# Autogenerated file
def render(data):
    yield """<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>ESPlorer</title>
    <link rel=\"stylesheet\" href=\"static/css/index.css\" />
    <meta http-equiv=\"refresh\" content=\"5\">
</head>
<body>
    <div class=\"wrapper\">
        <div class=\"container\">
            <div class=\"device\">
                <div class=\"device__header\">
                    Управление электрокамином
                </div>
                <div class=\"device__body\">
                    <div class=\"left-buttons\">
                        <div class=\"left-slider\"><br>
                            <label>Вкл/выкл</label><br>
                            <label class=\"switch\">
                                <input type=\"checkbox\" id=\"power\" onclick=\"workSwitch()\" """
    if data['work'] == 1:
        yield """ checked """
    yield """>
                                <span class=\"slider round\"></span>
                            </label><br>
                            <label></label>
                        </div>
                        <button class=\"btns\" id=\"soundp\" onclick=\"soundInc()\">
                            Звук+
                        </button>
                        <button class=\"btns\" id=\"brightp\" onclick=\"brightInc()\">
                            Яркость+
                        </button>
                    </div>
                    <div class=\"right-buttons\">
                        <button class=\"btns\" id=\"cooler\" onclick=\"coolerInc()\">
                            Кулер
                        </button>
                        <button class=\"btns\" id=\"soundm\" onclick=\"soundDecr()\">
                            Звук-
                        </button>
                        <button class=\"btns\" id=\"brightn\" onclick=\"brightDecr()\">
                            Яркость-
                        </button>
                    </div>
                </div>
                
                <div class=\"device__circles\">
                    <button class=\"device__circles-1\" onclick=\"yellow()\">
                    </button>
                    <button class=\"device__circles-2\" onclick=\"blue()\">
                    </button>
                    <button class=\"device__circles-3\" onclick=\"red()\">
                    </button>
                    <button class=\"device__circles-4\" onclick=\"orange()\">
                    </button>
                    <button class=\"device__circles-5\" onclick=\"green()\">
                    </button>
                </div>
                <div class=\"device__footer\">
                    LLC \"ELECTRONIC DEVICES\", UZBEKISTAN
                </div>
            </div>
        </div>
    </div>
    <h4>Work: """
    yield str(data['work'])
    yield """</h4>
    <h4>Cooler: """
    yield str(data['cooler'])
    yield """</h4>
    <h4>Color: """
    yield str(data['color'])
    yield """</h4>
    <h4>Brightness: """
    yield str(data['brightness'])
    yield """</h4>
    <h4>Volume: """
    yield str(data['volume'])
    yield """</h4>
    <h4>Charge: """
    yield str(data['charge'])
    yield """</h4>
    <h4>Discharge: """
    yield str(data['discharge'])
    yield """</h4>
    <h4>Pumps state:</h4> 
        """
    for pump in data['pumps']:
        yield """            <li>
                <p> """
        yield str(pump)
        yield """ </p>
            </li>
        """
    yield """    <script src=\"static/js/index.js\"></script>
</body>
</html>
"""
